#!/bin/bash
set -e

RUN_DIR=$(pwd)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/set-node-version

(
  # select a version of node
  source_nvm
  nvm install
  nvm use

  cd $DIR/../cdk

  npm install -g yarn

  # These options are a workaround for a yarn issue
  # See https://github.com/yarnpkg/yarn/issues/6312
  yarn --network-concurrency 1 --frozen-lockfile

  yarn test
  yarn synth
)
