#!/bin/bash
set -e

RUN_DIR=$(pwd)
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

nvm_available() {
  type -t nvm > /dev/null
}

source_nvm() {
  if ! nvm_available; then
    [ -e "/usr/local/opt/nvm/nvm.sh" ] && source /usr/local/opt/nvm/nvm.sh
  fi
  if ! nvm_available; then
    [ -e "$HOME/.nvm/nvm.sh" ] && source $HOME/.nvm/nvm.sh
  fi
}

(
  cd $DIR/../cdk

  # select a version of node
  source_nvm
  nvm install
  nvm use

  npm install -g yarn

  # These options are a workaround for a yarn issue
  # See https://github.com/yarnpkg/yarn/issues/6312
  yarn --network-concurrency 1 --frozen-lockfile
  # yarn build
  # yarn test

  yarn synth
)
