#!/bin/sh -e

set -e

function setupTestDeps {
  docker-compose up -d
  # Ensure localstack is up, and relevant resources have been created
  for ATTEMPT in {1..5}
  do
    pg_isready -h localhost -p 5432 --quiet -t 5 && echo "Postgres DB – ready" && break
    echo "Postgres DB – waiting ($ATTEMPT/5)"
    sleep 5
  done
}

function teardownTestDeps {
  docker-compose down
}

function buildClients {
  (cd rule-manager/rule-manager-client && npm i && npm run build)
  (cd rule-audit-client && npm i && npm run build)
}

function buildSbt {
  sbt clean compile test riffRaffNotifyTeamcity
}

function setup {
  setupTestDeps
  buildClients
  buildSbt
  teardownTestDeps
}

function teardown {
  teardownTestDeps
}

trap teardown EXIT

setup
teardown
