#!/bin/bash -e

printf "⚙️  Running dev-nginx setup\n"
dev-nginx setup-app ./nginx/nginx-mapping.yml
printf "✅ dev-nginx setup complete\n"

ln -sfn  ../../script/hooks/pre-commit .git/hooks/pre-commit
printf "✅ Pre-commit hooks set up\n"

printf "⚙️  Downloading dictionary for local use\n"
{
    aws s3 cp --profile composer --region eu-west-1 s3://typerighter-app-dev/dictionary/collins-dictionary.xml ~/.gu/typerighter/collins-dictionary.xml &&
    aws s3 cp --profile composer --region eu-west-1 s3://typerighter-app-dev/dictionary/collins-lemmatised-list.xml ~/.gu/typerighter/collins-lemmatised-list.xml &&

    printf "✅ Dictionary downloaded\n"
} || {
    printf "❌ Dictionary download failed. Are your Composer credentials up to date?\n"
}

printf "⚙️  Downloading 'words to not publish' for local use\n"
{
    aws s3 cp --profile composer --region eu-west-1 s3://typerighter-app-dev/dictionary/words-to-not-publish.json ~/.gu/typerighter/words-to-not-publish.json &&
    printf "✅ 'Words to not publish' for local use downloaded\n"
} || {
    printf "❌ 'Words to not publish' download failed. Are your Composer credentials up to date?\n"
}

