#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

APP_FOLDER="apps"

IS_DEBUG=false

for arg in "$@"
do
  if [[ "$arg" == "--debug" ]]; then
    IS_DEBUG=true
    shift
  fi
done

makeChecks() {
  . "${DIR}"/lib/check
}

setupDependencies() {
  docker-compose up -d
  (cd $APP_FOLDER/rule-manager/client && npm i && npm run start &)
}

teardownDependencies() {
  docker-compose down
  kill -9 $(lsof -ti:9100) # terminates the rule manager app
}

runRuleManager() {
  if [[ "$IS_DEBUG" = true ]] ; then
    sbt -jvm-debug 5006 "rule-manager / run"
  else
    sbt "rule-manager / run"
  fi
}

trap teardownDependencies EXIT
trap teardownDependencies INT TERM

makeChecks
printf "🚀 Rule manager will be available at https://manager.typerighter.local.dev-gutools.co.uk when ready\n"
setupDependencies
runRuleManager

# catches script exit events and kills child processes and their process trees
# https://stackoverflow.com/a/22644006
trap "exit" INT TERM
trap "kill 0" EXIT
