#!/bin/bash -e

IS_DEBUG=false
for arg in "$@"
do
  if [[ "$arg" == "--debug" ]]; then
    IS_DEBUG=true
    shift
  fi
done

checkCredentials() {
  STATUS=$(aws sts get-caller-identity --profile composer 2>&1 || true)
  if [[ ${STATUS} =~ (ExpiredToken) ]]; then
    echo -e "${red}Credentials for the composer profile are expired. Please fetch new credentials and run this again.${plain}"
    exit 1
  elif [[ ${STATUS} =~ ("could not be found") ]]; then
    echo -e "${red}Credentials for the composer profile are missing. Please ensure you have the right credentials.${plain}"
    exit 1
  fi
}

setupDependencies() {
  docker-compose up -d
  (cd rule-manager/rule-manager-client && npm i && npm run build)
}

teardownDependencies() {
  docker-compose down
}

runApp() {
  if [[ "$IS_DEBUG" = true ]] ; then
    sbt -jvm-debug 5005 run
  else
    sbt "checker / run"
  fi
}

trap teardownDependencies EXIT

setupDependencies
runApp
