#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

IS_DEBUG=false
for arg in "$@"
do
  if [[ "$arg" == "--debug" ]]; then
    IS_DEBUG=true
    shift
  fi
done

makeChecks() {
  source "${DIR}"/lib/check
}

runChecker() {
  if [[ "$IS_DEBUG" = true ]]; then
    bash "${DIR}"/start-checker $1 --debug
  else
    bash "${DIR}"/start-checker $1
  fi
}

runRuleManager() {
  if [[ "$IS_DEBUG" = true ]]; then
    bash "${DIR}"/start-manager $1 --debug
  else
    bash "${DIR}"/start-manager $1
  fi
}

# Make checks once now, rather than in each start script
makeChecks
runChecker "--checks-complete" &
runRuleManager "--checks-complete"