#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

IS_DEBUG=false
for arg in "$@"
do
  if [[ "$arg" == "--debug" ]]; then
    IS_DEBUG=true
    shift
  fi
done

runChecker() {
  if [[ "$IS_DEBUG" = true ]]; then
    bash "${DIR}"/start-checker --debug
  else
    bash "${DIR}"/start-checker
  fi
}

runRuleManager() {
  if [[ "$IS_DEBUG" = true ]]; then
    bash "${DIR}"/start-manager --debug
  else
    bash "${DIR}"/start-manager
  fi
}

runChecker &
runRuleManager