-- !Ups

CREATE TABLE user_feedback (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app                         TEXT NOT NULL,
    stage                       TEXT NOT NULL,
    document_url                TEXT NOT NULL,
    feedback_message            TEXT NOT NULL,
    user_email                  TEXT NOT NULL,
    match_id                    TEXT,
    rule_id                     TEXT,
    document_id                 TEXT,
    matcher_type                TEXT,
    suggestion                  TEXT,
    match_is_marked_as_correct  BOOLEAN,
    match_is_advisory           BOOLEAN,
    match_has_replacement       BOOLEAN,
    matched_text                TEXT,
    match_context               TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- !Downs

DROP TABLE user_feedback;
