#!/bin/bash -e

LIB_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$LIB_DIR/check-aws-credentials"
source "$LIB_DIR/check-java-version"
source "$LIB_DIR/check-node-version"